[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter=@devcollab/shared build",
  "pnpm --filter=@devcollab/api exec prisma generate",
  "pnpm --filter=@devcollab/api build"
]

[start]
cmd = "pnpm --filter=@devcollab/api prisma migrate deploy && pnpm --filter=@devcollab/api start"
